const json = {
  success: true,
  resultCode: null,
  resultCodeParams: null,
  errorMessage: null,
  successMessage: null,
  map: {
    value: {
      enterprise: {
        qdgbjj: {
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "26432.72",
              lastPremium: "122443.21",
              growthValue: "-96010.49",
              growthRate: "-78.412261",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "857221.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "43761.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "46537.72",
              lastPremium: "1000.30",
              growthValue: "45537.42",
              growthRate: "4552.376287",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "64273.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "12713232.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "443073.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "3001.00",
              lastPremium: "1000.00",
              growthValue: "2001.00",
              growthRate: "200.100000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "84588.72",
              lastPremium: "1434656.93",
              growthValue: "-1350068.21",
              growthRate: "-94.103906",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "898201.32",
              lastPremium: "0.00",
              growthValue: "898201.32",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "44564.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "52039.72",
              lastPremium: "1000.30",
              growthValue: "51039.42",
              growthRate: "5102.411277",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "64273.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "12722532.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "443073.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "17501.00",
              lastPremium: "47376.98",
              growthValue: "-29875.98",
              growthRate: "-63.060119",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "25390.00",
              lastPremium: "1000.00",
              growthValue: "24390.00",
              growthRate: "2439.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        },
        qdgbjj1: {
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "26432.72",
              lastPremium: "122443.21",
              growthValue: "-96010.49",
              growthRate: "-78.412261",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "857221.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "43761.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "46537.72",
              lastPremium: "1000.30",
              growthValue: "45537.42",
              growthRate: "4552.376287",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "64273.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "12713232.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "443073.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "3001.00",
              lastPremium: "1000.00",
              growthValue: "2001.00",
              growthRate: "200.100000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "84588.72",
              lastPremium: "1434656.93",
              growthValue: "-1350068.21",
              growthRate: "-94.103906",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "898201.32",
              lastPremium: "0.00",
              growthValue: "898201.32",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "44564.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "52039.72",
              lastPremium: "1000.30",
              growthValue: "51039.42",
              growthRate: "5102.411277",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "64273.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "12722532.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "443073.44",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "17501.00",
              lastPremium: "47376.98",
              growthValue: "-29875.98",
              growthRate: "-63.060119",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "25390.00",
              lastPremium: "1000.00",
              growthValue: "24390.00",
              growthRate: "2439.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        },
        sum: {
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "22772.72",
              reportName: "车险",
              premium: "219602.88",
              lastPremium: "2874193.86",
              growthValue: "-2654590.98",
              growthRate: "1678.408582",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "0.00",
              reportName: "货运险",
              premium: "1954902.96",
              lastPremium: "0.00",
              growthValue: "1796402.64",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "0.00",
              reportName: "家财险",
              premium: "115546.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "0.00",
              reportName: "企业财产险",
              premium: "130496.16",
              lastPremium: "2000.60",
              growthValue: "102078.84",
              growthRate: "10204.822554",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "0.00",
              reportName: "短期健康险",
              premium: "181380.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "0.00",
              reportName: "短期意外险",
              premium: "25445064.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "0.00",
              reportName: "个人寿险",
              premium: "938980.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "0.00",
              reportName: "责任险",
              premium: "35002.00",
              lastPremium: "94753.96",
              growthValue: "-59751.96",
              growthRate: "-126.120238",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "0.00",
              reportName: "船舶险",
              premium: "50780.00",
              lastPremium: "2000.00",
              growthValue: "48780.00",
              growthRate: "4878.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "0.00",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "0.00",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "103290.88",
              lastPremium: "244886.42",
              growthValue: "-192020.98",
              growthRate: "-156.824522",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "1872942.96",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "113940.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "119492.16",
              lastPremium: "2000.60",
              growthValue: "91074.84",
              growthRate: "9104.752574",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "181380.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "25426464.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "938980.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "6002.00",
              lastPremium: "2000.00",
              growthValue: "4002.00",
              growthRate: "400.200000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "mzx",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "gzzrx",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        }
      },
      personal: {
        qdgbjj: {
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "25212.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "79250.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "25212.72",
              lastPremium: "2440.00",
              growthValue: "22772.72",
              growthRate: "933.308197",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "79250.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        },
        qdgbjj1: {
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "25212.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "79250.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "chx",
              reportName: "车险",
              premium: "25212.72",
              lastPremium: "2440.00",
              growthValue: "22772.72",
              growthRate: "933.308197",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "hyx",
              reportName: "货运险",
              premium: "79250.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "jcx",
              reportName: "家财险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "qyccx",
              reportName: "企业财产险",
              premium: "13208.36",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "dqjkx",
              reportName: "短期健康险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "dqywx",
              reportName: "短期意外险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "grsx",
              reportName: "个人寿险",
              premium: "26416.72",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "zrx",
              reportName: "责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "cbx",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        },
        sum: {
          year: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "22772.72",
              reportName: "车险",
              premium: "219602.88",
              lastPremium: "2874193.86",
              growthValue: "-2654590.98",
              growthRate: "1678.408582",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "0.00",
              reportName: "货运险",
              premium: "1954902.96",
              lastPremium: "0.00",
              growthValue: "1796402.64",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "0.00",
              reportName: "家财险",
              premium: "115546.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "0.00",
              reportName: "企业财产险",
              premium: "130496.16",
              lastPremium: "2000.60",
              growthValue: "102078.84",
              growthRate: "10204.822554",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "0.00",
              reportName: "短期健康险",
              premium: "181380.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "0.00",
              reportName: "短期意外险",
              premium: "25445064.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "0.00",
              reportName: "个人寿险",
              premium: "938980.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "0.00",
              reportName: "责任险",
              premium: "35002.00",
              lastPremium: "94753.96",
              growthValue: "-59751.96",
              growthRate: "-126.120238",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "0.00",
              reportName: "船舶险",
              premium: "50780.00",
              lastPremium: "2000.00",
              growthValue: "48780.00",
              growthRate: "4878.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "0.00",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "0.00",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ],
          month: [
            {
              id: "1",
              reportValue: "1",
              reportCode: "0.00",
              reportName: "车险",
              premium: "103290.88",
              lastPremium: "244886.42",
              growthValue: "-192020.98",
              growthRate: "-156.824522",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "2",
              reportValue: "2",
              reportCode: "0.00",
              reportName: "货运险",
              premium: "1872942.96",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "3",
              reportValue: "3",
              reportCode: "0.00",
              reportName: "家财险",
              premium: "113940.16",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "4",
              reportValue: "4",
              reportCode: "0.00",
              reportName: "企业财产险",
              premium: "119492.16",
              lastPremium: "2000.60",
              growthValue: "91074.84",
              growthRate: "9104.752574",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "5",
              reportValue: "5",
              reportCode: "0.00",
              reportName: "短期健康险",
              premium: "181380.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "6",
              reportValue: "6",
              reportCode: "0.00",
              reportName: "短期意外险",
              premium: "25426464.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "7",
              reportValue: "7",
              reportCode: "0.00",
              reportName: "个人寿险",
              premium: "938980.32",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "8",
              reportValue: "8",
              reportCode: "0.00",
              reportName: "责任险",
              premium: "6002.00",
              lastPremium: "2000.00",
              growthValue: "4002.00",
              growthRate: "400.200000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "9",
              reportValue: "9",
              reportCode: "0.00",
              reportName: "船舶险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "10",
              reportValue: "10",
              reportCode: "0.00",
              reportName: "码责险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            },
            {
              id: "11",
              reportValue: "11",
              reportCode: "0.00",
              reportName: "雇主责任险",
              premium: "0.00",
              lastPremium: "0.00",
              growthValue: "0.00",
              growthRate: "0.000000",
              totalSumInsured: null,
              lastTotalSumInsured: null,
              seqNum: null
            }
          ]
        }
      }
    }
  }
};
export default json;
